# Generated by Django 4.2.7 on 2026-01-11 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные при встрече'), ('card_mir', 'Картой МИР онлайн'), ('card_other', 'Другой картой онлайн'), ('not_selected', 'Не выбран')], default='not_selected', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(default='not_paid', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус регистрации'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card_mir', 'Карта МИР'), ('card_other', 'Другая карта')], max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('completed', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращено')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID транзакции')),
                ('bank_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ банка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='events.registration', verbose_name='Регистрация')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
