# Generated by Django 4.2.7 on 2026-01-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ответ на возврат'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID возврата'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Возвращено'),
        ),
        migrations.AddField(
            model_name='registration',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='registration',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('completed', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращено'), ('refund_pending', 'Ожидает возврата')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('refunded', 'Средства возвращены')], default='pending', max_length=20, verbose_name='Статус регистрации'),
        ),
    ]
